---
title: "Bike Data Cleaning"
output:
  html_notebook: default
  pdf_document: default
author: "Philipp Schaad"
---

In this file we will analyze and clean up the data. At the end of the file the data will be saved and ready for furhter analysis with the different models we have to apply.

## Import libraries 
```{r}
#install.packages("tidyverse")
#install.packages("Hmisc")
library(tidyverse)
library(readr)
library(Hmisc)
library(dplyr)
library(plyr)

```

## import files
```{r}
bikeshare.trip.2011 <- read_csv("../Data/2011-capitalbikeshare-tripdata.csv")
bikeshare.trip.2012.1 <- read_csv("../Data/2012-capitalbikeshare-tripdata/2012Q1-capitalbikeshare-tripdata.csv")
bikeshare.trip.2012.2 <- read_csv("../Data/2012-capitalbikeshare-tripdata/2012Q2-capitalbikeshare-tripdata.csv")
bikeshare.trip.2012.3 <- read_csv("../Data/2012-capitalbikeshare-tripdata/2012Q3-capitalbikeshare-tripdata.csv")
bikeshare.trip.2012.4 <- read_csv("../Data/2012-capitalbikeshare-tripdata/2012Q4-capitalbikeshare-tripdata.csv")
bikeshare.houerli <- read.csv("../Data/hour.csv")
bikeshare.daily <- read.csv("../Data/day.csv")

```


```{r}
View()
class(bikeshare.daily)
class(bikeshare.trip.2012.3)

summary(bikeshare.daily)
str(bikeshare.daily)
summary(bikeshare.houerli)
str(bikeshare.houerli)
summary(bikeshare.trip.2011)
str(bikeshare.trip.2011)
summary(bikeshare.trip.2012.1)
str(bikeshare.trip.2012.1)
summary(bikeshare.trip.2012.2)
str(bikeshare.trip.2012.2)
summary(bikeshare.trip.2012.3)
str(bikeshare.trip.2012.3)
summary(bikeshare.trip.2012.4)
str(bikeshare.trip.2012.4)
```


### Merge tripdata into one dataframe
```{r}
trip.all.years <- list.files(path = "../Data/tripdata",     # Identify all csv files in folder
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                            # Store all files in list
  bind_rows                                                       # Combine data sets into one data set

```

### Export merged tripdata to csv
```{r}
is.data.frame(trip.all.years)
write.csv(trip.all.years,"../Data/tripdata/capitalbikeshare-tripdata-all.csv", row.names = TRUE)

```