---
title: "Neural Net"
output: html_notebook
author: "Régis Michael Andreoli"
---


Load libraries and data set

```{r, echo= FALSE}
library(tidyverse)
library(neuralnet)
library(caret)
library(rstudioapi)
library(rmarkdown)
library(dplyr)
```
Load and inspect data

```{r, echo= FALSE}
d <- setwd(dirname(getActiveDocumentContext()$path))
df <- read.csv("../Data/hour.csv")
```


--------------------------------------------------------------------------------
# Adjust variables type
```{r, echo= FALSE}
df$season <- as.factor(df$season)
df$yr <- as.factor(df$yr)
df$mnth <- as.factor(df$mnth)
df$hr <- as.factor(df$hr)
df$holiday <- as.factor(df$holiday)
df$weekday <- as.factor(df$weekday)
df$workingday <- as.factor(df$workingday)
df$weathersit <- as.factor(df$weathersit)
df$cnt <- as.numeric(df$cnt)
```

# normalize count
```{r, echo= FALSE}
```

# Identifying near-zero variance variable
```{r}
nearZeroVar(df, saveMetrics = TRUE)
```

```{r, echo= FALSE}
str(df)
```

--------------------------------------------------------------------------------

#Split data in train & test partition
```{r}
df$cnt <- (df$cnt - min(df$cnt)) / (max(df$cnt) - min(df$cnt))
str(df)
```

```{r}
set.seed(123)
indices <- createDataPartition(df$cnt, p=.1, list = F)

train <- df %>% slice(indices)
test <- df %>% slice(-indices)

str(train)
```

--------------------------------------------------------------------------------
# ANN Model 1 - With Caret

```{r}
set.seed(42)
tuGrid <- expand.grid(.layer1=c(1:6), .layer2=c(1:6), .layer3=c(0:3))

trCtrl <- trainControl(
  method = 'repeatedcv',
  number = 2,
  repeats = 2,
  returnResamp = 'final'
)
```


```{r}
models <- train(cnt ~ weekday + weathersit, data = train,
  method = 'neuralnet', metric = 'RMSE',
  linear.output = TRUE,
  preProcess = c('center', 'scale'),
  tuneGrid = tuGrid,
  trControl = trCtrl
  )
```

```{r}
plot(models)
```
# ANN Model 2 - With Caret - Model to predict amount of rents only due to date variables

```{r}
tuGrid_2 <- expand.grid(.layer1=c(4:4), .layer2=c(3:4), .layer3=c(0:0))

trCtrl_2 <- trainControl(
  method = 'repeatedcv',
  number = 2,
  repeats = 2,
  returnResamp = 'final'
)
```

```{r}
models_2 <- train(cnt ~ hr + weekday + mnth, data = train,
  method = 'neuralnet', metric = 'RMSE',
  linear.output = TRUE,
  preProcess = c('center', 'scale'),
  tuneGrid = tuGrid_2,
  trControl = trCtrl_2
  )
```

```{r}
plot(models_2)
```

